###############################################
# Itero Power-Up — Netlify Configuration
###############################################

[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

###############################################
# Redirects
###############################################

# Allow these files to load directly (avoid redirect to SPA)
# toast assets MUST bypass the SPA rule
[[redirects]]
  from = "/toast.html"
  to = "/toast.html"
  status = 200

[[redirects]]
  from = "/toast.js"
  to = "/toast.js"
  status = 200

[[redirects]]
  from = "/toast.css"
  to = "/toast.css"
  status = 200
  
[[redirects]]
  from = "/popup.html"
  to = "/popup.html"
  status = 200

[[redirects]]
  from = "/powerup.js"
  to = "/powerup.js"
  status = 200

[[redirects]]
  from = "/dashboard-wrapper.html"
  to = "/dashboard-wrapper.html"
  status = 200

[[redirects]]
  from = "/settings.html"
  to = "/settings.html"
  status = 200

# Catch-all SPA rule (keep last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

###############################################
# Default headers (global)
###############################################

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options    = "nosniff"
    Referrer-Policy           = "strict-origin-when-cross-origin"
    Permissions-Policy        = "camera=(), microphone=(), geolocation=()"

    # ✅ Global Content Security Policy
    # This CSP is designed for Trello Power-Ups — allows embedding inside Trello
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      object-src 'none';
      frame-ancestors https://trello.com https://*.trello.com;

      script-src 'self' https://p.trellocdn.com;
      script-src-elem 'self' https://p.trellocdn.com;


      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https:;
      font-src 'self' data: https:;

      connect-src
        'self'
        https://api.trello.com
        https://auth.atlassian.com
        https://id.atlassian.com
        https://trello.com
        https://*.trello.com
        https://itero-api-fme7.onrender.com
        https://itero-api-dev.onrender.com
        https://itero-api-dev-zg94.onrender.com;

      upgrade-insecure-requests;
    """

###############################################
# File-specific headers
###############################################

[[headers]]
  for = "/powerup.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/popup.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

###############################################
# Contexts (optional overrides if needed)
###############################################

# Production — inherits global headers, no extra rules required
[context.production]

# Development branch — inherits global headers
[context."dev"]

# Deploy previews — inherits global headers
[context.deploy-preview]
