[build]
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/powerup.js"
  to = "/powerup.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
