[build]
  publish = "frontend/dist"
  command = "npm run build"

[[redirects]]
  from = "/powerup.js"
  to = "/public/powerup.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
