###############################################
# Itero Power-Up — Netlify Configuration
###############################################

[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

###############################################
# ✅ REDIRECTS
###############################################

# --- Exceptions: must come BEFORE the SPA catch-all ---
# Prevent popup and SDK files from being redirected to /index.html

[[redirects]]
  from = "/popup.html"
  to = "/popup.html"
  status = 200

[[redirects]]
  from = "/powerup.js"
  to = "/powerup.js"
  status = 200

[[redirects]]
  from = "/dashboard-wrapper.html"
  to = "/dashboard-wrapper.html"
  status = 200

[[redirects]]
  from = "/settings.html"
  to = "/settings.html"
  status = 200

# --- SPA fallback ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

###############################################
# ✅ DEFAULT HEADERS (apply globally)
###############################################

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Explicit MIME types (optional but clean)
[[headers]]
  for = "/powerup.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/popup.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

###############################################
# ✅ SECURITY HEADERS BY CONTEXT
###############################################

# ---------- PRODUCTION ----------
[context.production]
  [[context.production.headers]]
    for = "/*"
    [context.production.headers.values]
      Content-Security-Policy = """
default-src 'self';
frame-ancestors https://trello.com https://*.trello.com;
script-src 'self' https://p.trellocdn.com;
script-src-elem 'self' https://p.trellocdn.com;
style-src 'self' 'unsafe-inline';
img-src 'self' data: https:;
font-src 'self' data: https:;
connect-src 'self' https://api.trello.com https://itero-api-fme7.onrender.com;
object-src 'none';
base-uri 'none';
form-action 'self';
upgrade-insecure-requests
"""

# ---------- DEV / UI-REDESIGN BRANCH ----------
[context."ui-redesign"]
  [[context."ui-redesign".headers]]
    for = "/*"
    [context."ui-redesign".headers.values]
      Content-Security-Policy = """
default-src 'self';
frame-ancestors https://trello.com https://*.trello.com;
script-src 'self' https://p.trellocdn.com;
script-src-elem 'self' https://p.trellocdn.com;
style-src 'self' 'unsafe-inline';
img-src 'self' data: https:;
font-src 'self' data: https:;
connect-src 'self' https://api.trello.com https://itero-api-dev.onrender.com https://itero-api-dev-zg94.onrender.com;
object-src 'none';
base-uri 'none';
form-action 'self';
upgrade-insecure-requests
"""

###############################################
# ✅ NOTES
###############################################
# - The key fix: popup.html and powerup.js must NOT be caught by /* → /index.html
# - CSP allows https://p.trellocdn.com so Trello SDK can load.
# - Add new API domains to connect-src when needed.
# - To debug quickly: open https://your-site.netlify.app/popup.html → console → !!window.TrelloPowerUp should be true.
