name: Trello Compliance Poller

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (UTC)
  workflow_dispatch:         # lets you run it manually

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Call compliance endpoint
        run: |
          curl -sS -i -X POST "https://itero-api-fm7.onrender.com/api/users/compliance/run-now" \
            -H "X-Admin-Token: ${{ secrets.ADMIN_JOB_TOKEN }}" \
            --fail
