name: Trello Compliance Poller

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours UTC
  workflow_dispatch:         # allow manual trigger

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Call compliance endpoint
        run: |
          set -euo pipefail
          curl -sS -i -X POST "${{ secrets.API_BASE_URL }}/api/users/compliance/run-now" \
            -H "X-Admin-Token: ${{ secrets.ADMIN_JOB_TOKEN }}" \
            --fail
